[package]
name = "ha-2-lexer"
version = "0.1.0"
authors = ["ivan tkachenko <i.tkachenko@innopolis.ru>", "Egor Ivkov <e.ivkov@innopolis.ru>"]

[dependencies]
regex = "^1.0"
ndarray = "0.11.0"
id_tree = "1.3.0"